name: Library Validation

# The workflow will run on every push and pull request to the repository
on:
  - push
  - pull_request

jobs:
  validate-library:
    runs-on: ubuntu-latest

    steps:
      # This step makes the contents of the repository available to the workflow
      - name: Checkout repository
        uses: actions/checkout@v5

      # Validate Arduino library structure and metadata
      - name: Validate Arduino Library
        uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update